// Static server for dist-lab with precompressed brotli/gzip support and sane cache
// headers. Replaces `vite preview` for the Tailscale/Funnel deployment: vite preview
// serves raw bytes; this serves the .br/.gz variants generated by precompress.mjs.
//
//   node scripts/serve-dist.mjs [port] [host]
//
// Defaults: port 4174, host 0.0.0.0 (tailnet + loopback; Funnel proxies to 127.0.0.1).
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize, resolve, sep } from 'node:path';

const port = Number(process.argv[2]) || 4174;
const host = process.argv[3] || '0.0.0.0';
const root = resolve(process.env.SERVE_ROOT || 'dist-lab');

const TYPES = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml', '.json': 'application/json', '.md': 'text/markdown; charset=utf-8',
  '.woff2': 'font/woff2', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png',
  '.webp': 'image/webp', '.hdr': 'application/octet-stream', '.exr': 'application/octet-stream',
  '.glb': 'model/gltf-binary', '.txt': 'text/plain; charset=utf-8', '.ico': 'image/x-icon',
};

const cacheFor = (path) => {
  if (path.includes(`${sep}assets${sep}`)) return 'public, max-age=31536000, immutable'; // hashed filenames
  if (extname(path) === '.html') return 'no-cache';
  return 'public, max-age=3600';
};

createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://x');
    let pathname = decodeURIComponent(url.pathname);
    if (pathname.endsWith('/')) pathname += 'index.html';
    const file = normalize(join(root, pathname));
    if (!file.startsWith(root + sep) && file !== root) { res.writeHead(403).end(); return; }
    let target = file;
    const info = await stat(file).catch(() => null);
    if (info?.isDirectory()) target = join(file, 'index.html');
    const accept = req.headers['accept-encoding'] || '';
    let encoding = null, ext = null;
    if (accept.includes('br') && await stat(`${target}.br`).catch(() => null)) { encoding = 'br'; ext = '.br'; }
    else if (accept.includes('gzip') && await stat(`${target}.gz`).catch(() => null)) { encoding = 'gzip'; ext = '.gz'; }
    const body = await readFile(ext ? `${target}${ext}` : target);
    res.writeHead(200, {
      'Content-Type': TYPES[extname(target)] || 'application/octet-stream',
      ...(encoding ? { 'Content-Encoding': encoding, Vary: 'Accept-Encoding' } : {}),
      'Cache-Control': cacheFor(target),
    });
    res.end(body);
  } catch (error) {
    console.log(`404: ${req.method} ${JSON.stringify(req.url)} — ${error.message}`);
    res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' }).end('No encontrado');
  }
}).listen(port, host, () => console.log(`Kineti dist-lab en http://${host}:${port} (brotli/gzip + cache)`));
